@URL = http://localhost:8000

###
GET {{URL}}/patients

###
GET {{URL}}/users

###
GET {{URL}}/patients/4

###
GET {{URL}}/patients/search?query=jane

###
POST {{URL}}/patients
Content-Type: application/json

{
    "dob": "1992-01-01",
    "gender": "male",
    "address": "12 Main ",
    "status": true,
    "user_id": 1
}

###
POST {{URL}}/users
Content-Type: application/json

{
    "first_name": "john",
    "last_name": "malek",
    "email": "malek@gmail.com",
    "password": "12345",
    "phone_number": 13456,
    "role": "patient",
    "status": "active"
}
###
PATCH {{URL}}/patients/4
Content-Type: application/json

{
    "last_name": "Jane"
}

###
DELETE {{URL}}/patients/2